// Code generated by go-swagger; DO NOT EDIT.

// Package restapi cards
//
//	This is a sample User's cards application based on the OpenAPI 2.0 specification.
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /api
//	Version: v1
//	Contact:
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
