// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCard new card
//
// swagger:model NewCard
type NewCard struct {

	// bank id
	// Example: 53aa35c8-e659-44b2-882f-f6056e443c99
	BankID string `json:"bank_id,omitempty"`

	// cvs
	// Example: 109
	Cvs string `json:"cvs,omitempty"`

	// number
	// Example: 4242424242424242
	Number uint64 `json:"number,omitempty"`

	// password
	// Example: 12345
	Password string `json:"password,omitempty"`

	// user id
	// Example: 53aa35c8-e659-44b2-882f-f6056e443c99
	UserID string `json:"user_id,omitempty"`

	// user name
	// Example: JOHN DOE
	UserName string `json:"user_name,omitempty"`

	// valid
	// Example: 03/23
	Valid string `json:"valid,omitempty"`
}

// Validate validates this new card
func (m *NewCard) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new card based on context it is used
func (m *NewCard) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewCard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewCard) UnmarshalBinary(b []byte) error {
	var res NewCard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
