// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewBank new bank
//
// swagger:model NewBank
type NewBank struct {

	// address
	// Example: Moscow, Kremlin
	Address string `json:"address,omitempty"`

	// bik
	// Example: 44525974
	Bik uint32 `json:"bik,omitempty"`

	// name
	// Example: Main Bank
	Name string `json:"name,omitempty"`

	// telephone
	// Example: 565-56-56
	Telephone string `json:"telephone,omitempty"`
}

// Validate validates this new bank
func (m *NewBank) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new bank based on context it is used
func (m *NewBank) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewBank) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewBank) UnmarshalBinary(b []byte) error {
	var res NewBank
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
