// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cards/internal/infrastructure/swagger/models"
)

// AddBankOKCode is the HTTP code returned for type AddBankOK
const AddBankOKCode int = 200

/*
AddBankOK Successful operation

swagger:response addBankOK
*/
type AddBankOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bank `json:"body,omitempty"`
}

// NewAddBankOK creates AddBankOK with default headers values
func NewAddBankOK() *AddBankOK {

	return &AddBankOK{}
}

// WithPayload adds the payload to the add bank o k response
func (o *AddBankOK) WithPayload(payload *models.Bank) *AddBankOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add bank o k response
func (o *AddBankOK) SetPayload(payload *models.Bank) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddBankOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddBankBadRequestCode is the HTTP code returned for type AddBankBadRequest
const AddBankBadRequestCode int = 400

/*
AddBankBadRequest Invalid input

swagger:response addBankBadRequest
*/
type AddBankBadRequest struct {
}

// NewAddBankBadRequest creates AddBankBadRequest with default headers values
func NewAddBankBadRequest() *AddBankBadRequest {

	return &AddBankBadRequest{}
}

// WriteResponse to the client
func (o *AddBankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddBankUnprocessableEntityCode is the HTTP code returned for type AddBankUnprocessableEntity
const AddBankUnprocessableEntityCode int = 422

/*
AddBankUnprocessableEntity Validation exception

swagger:response addBankUnprocessableEntity
*/
type AddBankUnprocessableEntity struct {
}

// NewAddBankUnprocessableEntity creates AddBankUnprocessableEntity with default headers values
func NewAddBankUnprocessableEntity() *AddBankUnprocessableEntity {

	return &AddBankUnprocessableEntity{}
}

// WriteResponse to the client
func (o *AddBankUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
