// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteBankHandlerFunc turns a function with the right signature into a delete bank handler
type DeleteBankHandlerFunc func(DeleteBankParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBankHandlerFunc) Handle(params DeleteBankParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteBankHandler interface for that can handle valid delete bank params
type DeleteBankHandler interface {
	Handle(DeleteBankParams, interface{}) middleware.Responder
}

// NewDeleteBank creates a new http.Handler for the delete bank operation
func NewDeleteBank(ctx *middleware.Context, handler DeleteBankHandler) *DeleteBank {
	return &DeleteBank{Context: ctx, Handler: handler}
}

/*
	DeleteBank swagger:route DELETE /bank/{bankId} bank deleteBank

# Deletes a bank

delete a bank
*/
type DeleteBank struct {
	Context *middleware.Context
	Handler DeleteBankHandler
}

func (o *DeleteBank) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteBankParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
