// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBankBadRequestCode is the HTTP code returned for type DeleteBankBadRequest
const DeleteBankBadRequestCode int = 400

/*
DeleteBankBadRequest Invalid bank value

swagger:response deleteBankBadRequest
*/
type DeleteBankBadRequest struct {
}

// NewDeleteBankBadRequest creates DeleteBankBadRequest with default headers values
func NewDeleteBankBadRequest() *DeleteBankBadRequest {

	return &DeleteBankBadRequest{}
}

// WriteResponse to the client
func (o *DeleteBankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
