// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteBankParams creates a new DeleteBankParams object
//
// There are no default values defined in the spec.
func NewDeleteBankParams() DeleteBankParams {

	return DeleteBankParams{}
}

// DeleteBankParams contains all the bound params for the delete bank operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteBank
type DeleteBankParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Bank uuid to delete
	  Required: true
	  In: path
	*/
	BankID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteBankParams() beforehand.
func (o *DeleteBankParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBankID, rhkBankID, _ := route.Params.GetOK("bankId")
	if err := o.bindBankID(rBankID, rhkBankID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBankID binds and validates parameter BankID from path.
func (o *DeleteBankParams) bindBankID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("bankId", "path", "int64", raw)
	}
	o.BankID = value

	return nil
}
