// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetBankByIDParams creates a new GetBankByIDParams object
//
// There are no default values defined in the spec.
func NewGetBankByIDParams() GetBankByIDParams {

	return GetBankByIDParams{}
}

// GetBankByIDParams contains all the bound params for the get bank by ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters getBankByID
type GetBankByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of bank to return
	  Required: true
	  In: path
	*/
	BankID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBankByIDParams() beforehand.
func (o *GetBankByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBankID, rhkBankID, _ := route.Params.GetOK("bankId")
	if err := o.bindBankID(rBankID, rhkBankID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBankID binds and validates parameter BankID from path.
func (o *GetBankByIDParams) bindBankID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.BankID = raw

	return nil
}
