// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBankByUUIDHandlerFunc turns a function with the right signature into a get bank by UUID handler
type GetBankByUUIDHandlerFunc func(GetBankByUUIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBankByUUIDHandlerFunc) Handle(params GetBankByUUIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetBankByUUIDHandler interface for that can handle valid get bank by UUID params
type GetBankByUUIDHandler interface {
	Handle(GetBankByUUIDParams, interface{}) middleware.Responder
}

// NewGetBankByUUID creates a new http.Handler for the get bank by UUID operation
func NewGetBankByUUID(ctx *middleware.Context, handler GetBankByUUIDHandler) *GetBankByUUID {
	return &GetBankByUUID{Context: ctx, Handler: handler}
}

/*
	GetBankByUUID swagger:route GET /bank/{bankId} bank getBankByUuid

# Find bank by uuid

Returns a single bank
*/
type GetBankByUUID struct {
	Context *middleware.Context
	Handler GetBankByUUIDHandler
}

func (o *GetBankByUUID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBankByUUIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
