// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBankByIDHandlerFunc turns a function with the right signature into a get bank by ID handler
type GetBankByIDHandlerFunc func(GetBankByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBankByIDHandlerFunc) Handle(params GetBankByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetBankByIDHandler interface for that can handle valid get bank by ID params
type GetBankByIDHandler interface {
	Handle(GetBankByIDParams, interface{}) middleware.Responder
}

// NewGetBankByID creates a new http.Handler for the get bank by ID operation
func NewGetBankByID(ctx *middleware.Context, handler GetBankByIDHandler) *GetBankByID {
	return &GetBankByID{Context: ctx, Handler: handler}
}

/*
	GetBankByID swagger:route GET /bank/{bankId} bank getBankById

# Find bank by id

Returns a single bank
*/
type GetBankByID struct {
	Context *middleware.Context
	Handler GetBankByIDHandler
}

func (o *GetBankByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBankByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
