// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cfif1982/cards/internal/infrastructure/swagger/models"
)

// GetBankByIDOKCode is the HTTP code returned for type GetBankByIDOK
const GetBankByIDOKCode int = 200

/*
GetBankByIDOK successful operation

swagger:response getBankByIdOK
*/
type GetBankByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bank `json:"body,omitempty"`
}

// NewGetBankByIDOK creates GetBankByIDOK with default headers values
func NewGetBankByIDOK() *GetBankByIDOK {

	return &GetBankByIDOK{}
}

// WithPayload adds the payload to the get bank by Id o k response
func (o *GetBankByIDOK) WithPayload(payload *models.Bank) *GetBankByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bank by Id o k response
func (o *GetBankByIDOK) SetPayload(payload *models.Bank) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBankByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBankByIDBadRequestCode is the HTTP code returned for type GetBankByIDBadRequest
const GetBankByIDBadRequestCode int = 400

/*
GetBankByIDBadRequest Invalid ID supplied

swagger:response getBankByIdBadRequest
*/
type GetBankByIDBadRequest struct {
}

// NewGetBankByIDBadRequest creates GetBankByIDBadRequest with default headers values
func NewGetBankByIDBadRequest() *GetBankByIDBadRequest {

	return &GetBankByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetBankByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetBankByIDNotFoundCode is the HTTP code returned for type GetBankByIDNotFound
const GetBankByIDNotFoundCode int = 404

/*
GetBankByIDNotFound Bank not found

swagger:response getBankByIdNotFound
*/
type GetBankByIDNotFound struct {
}

// NewGetBankByIDNotFound creates GetBankByIDNotFound with default headers values
func NewGetBankByIDNotFound() *GetBankByIDNotFound {

	return &GetBankByIDNotFound{}
}

// WriteResponse to the client
func (o *GetBankByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
