// Code generated by go-swagger; DO NOT EDIT.

package bank

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cfif1982/cards/internal/infrastructure/swagger/models"
)

// UpdateBankOKCode is the HTTP code returned for type UpdateBankOK
const UpdateBankOKCode int = 200

/*
UpdateBankOK Successful operation

swagger:response updateBankOK
*/
type UpdateBankOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bank `json:"body,omitempty"`
}

// NewUpdateBankOK creates UpdateBankOK with default headers values
func NewUpdateBankOK() *UpdateBankOK {

	return &UpdateBankOK{}
}

// WithPayload adds the payload to the update bank o k response
func (o *UpdateBankOK) WithPayload(payload *models.Bank) *UpdateBankOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update bank o k response
func (o *UpdateBankOK) SetPayload(payload *models.Bank) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBankOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateBankBadRequestCode is the HTTP code returned for type UpdateBankBadRequest
const UpdateBankBadRequestCode int = 400

/*
UpdateBankBadRequest Invalid ID supplied

swagger:response updateBankBadRequest
*/
type UpdateBankBadRequest struct {
}

// NewUpdateBankBadRequest creates UpdateBankBadRequest with default headers values
func NewUpdateBankBadRequest() *UpdateBankBadRequest {

	return &UpdateBankBadRequest{}
}

// WriteResponse to the client
func (o *UpdateBankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateBankNotFoundCode is the HTTP code returned for type UpdateBankNotFound
const UpdateBankNotFoundCode int = 404

/*
UpdateBankNotFound Bank not found

swagger:response updateBankNotFound
*/
type UpdateBankNotFound struct {
}

// NewUpdateBankNotFound creates UpdateBankNotFound with default headers values
func NewUpdateBankNotFound() *UpdateBankNotFound {

	return &UpdateBankNotFound{}
}

// WriteResponse to the client
func (o *UpdateBankNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateBankUnprocessableEntityCode is the HTTP code returned for type UpdateBankUnprocessableEntity
const UpdateBankUnprocessableEntityCode int = 422

/*
UpdateBankUnprocessableEntity Validation exception

swagger:response updateBankUnprocessableEntity
*/
type UpdateBankUnprocessableEntity struct {
}

// NewUpdateBankUnprocessableEntity creates UpdateBankUnprocessableEntity with default headers values
func NewUpdateBankUnprocessableEntity() *UpdateBankUnprocessableEntity {

	return &UpdateBankUnprocessableEntity{}
}

// WriteResponse to the client
func (o *UpdateBankUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
