// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cards/internal/infrastructure/swagger/models"
)

// AddUserOKCode is the HTTP code returned for type AddUserOK
const AddUserOKCode int = 200

/*
AddUserOK Successful operation

swagger:response addUserOK
*/
type AddUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewAddUserOK creates AddUserOK with default headers values
func NewAddUserOK() *AddUserOK {

	return &AddUserOK{}
}

// WithPayload adds the payload to the add user o k response
func (o *AddUserOK) WithPayload(payload *models.User) *AddUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add user o k response
func (o *AddUserOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddUserBadRequestCode is the HTTP code returned for type AddUserBadRequest
const AddUserBadRequestCode int = 400

/*
AddUserBadRequest Invalid input

swagger:response addUserBadRequest
*/
type AddUserBadRequest struct {
}

// NewAddUserBadRequest creates AddUserBadRequest with default headers values
func NewAddUserBadRequest() *AddUserBadRequest {

	return &AddUserBadRequest{}
}

// WriteResponse to the client
func (o *AddUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddUserUnprocessableEntityCode is the HTTP code returned for type AddUserUnprocessableEntity
const AddUserUnprocessableEntityCode int = 422

/*
AddUserUnprocessableEntity Validation exception

swagger:response addUserUnprocessableEntity
*/
type AddUserUnprocessableEntity struct {
}

// NewAddUserUnprocessableEntity creates AddUserUnprocessableEntity with default headers values
func NewAddUserUnprocessableEntity() *AddUserUnprocessableEntity {

	return &AddUserUnprocessableEntity{}
}

// WriteResponse to the client
func (o *AddUserUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
