// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cfif1982/cards/internal/infrastructure/swagger/models"
)

// GetUserByUUIDOKCode is the HTTP code returned for type GetUserByUUIDOK
const GetUserByUUIDOKCode int = 200

/*
GetUserByUUIDOK successful operation

swagger:response getUserByUuidOK
*/
type GetUserByUUIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetUserByUUIDOK creates GetUserByUUIDOK with default headers values
func NewGetUserByUUIDOK() *GetUserByUUIDOK {

	return &GetUserByUUIDOK{}
}

// WithPayload adds the payload to the get user by Uuid o k response
func (o *GetUserByUUIDOK) WithPayload(payload *models.User) *GetUserByUUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user by Uuid o k response
func (o *GetUserByUUIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserByUUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserByUUIDBadRequestCode is the HTTP code returned for type GetUserByUUIDBadRequest
const GetUserByUUIDBadRequestCode int = 400

/*
GetUserByUUIDBadRequest Invalid ID supplied

swagger:response getUserByUuidBadRequest
*/
type GetUserByUUIDBadRequest struct {
}

// NewGetUserByUUIDBadRequest creates GetUserByUUIDBadRequest with default headers values
func NewGetUserByUUIDBadRequest() *GetUserByUUIDBadRequest {

	return &GetUserByUUIDBadRequest{}
}

// WriteResponse to the client
func (o *GetUserByUUIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetUserByUUIDNotFoundCode is the HTTP code returned for type GetUserByUUIDNotFound
const GetUserByUUIDNotFoundCode int = 404

/*
GetUserByUUIDNotFound User not found

swagger:response getUserByUuidNotFound
*/
type GetUserByUUIDNotFound struct {
}

// NewGetUserByUUIDNotFound creates GetUserByUUIDNotFound with default headers values
func NewGetUserByUUIDNotFound() *GetUserByUUIDNotFound {

	return &GetUserByUUIDNotFound{}
}

// WriteResponse to the client
func (o *GetUserByUUIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
