// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUserByUUIDHandlerFunc turns a function with the right signature into a get user by UUID handler
type GetUserByUUIDHandlerFunc func(GetUserByUUIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserByUUIDHandlerFunc) Handle(params GetUserByUUIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserByUUIDHandler interface for that can handle valid get user by UUID params
type GetUserByUUIDHandler interface {
	Handle(GetUserByUUIDParams, interface{}) middleware.Responder
}

// NewGetUserByUUID creates a new http.Handler for the get user by UUID operation
func NewGetUserByUUID(ctx *middleware.Context, handler GetUserByUUIDHandler) *GetUserByUUID {
	return &GetUserByUUID{Context: ctx, Handler: handler}
}

/*
	GetUserByUUID swagger:route GET /user/{userId} user getUserByUuid

# Find user by uuid

Returns a single user
*/
type GetUserByUUID struct {
	Context *middleware.Context
	Handler GetUserByUUIDHandler
}

func (o *GetUserByUUID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUserByUUIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
