// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddCardHandlerFunc turns a function with the right signature into a add card handler
type AddCardHandlerFunc func(AddCardParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddCardHandlerFunc) Handle(params AddCardParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddCardHandler interface for that can handle valid add card params
type AddCardHandler interface {
	Handle(AddCardParams, interface{}) middleware.Responder
}

// NewAddCard creates a new http.Handler for the add card operation
func NewAddCard(ctx *middleware.Context, handler AddCardHandler) *AddCard {
	return &AddCard{Context: ctx, Handler: handler}
}

/*
	AddCard swagger:route POST /card card addCard

# Add a new card

Add a new card to the base
*/
type AddCard struct {
	Context *middleware.Context
	Handler AddCardHandler
}

func (o *AddCard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddCardParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
