// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteCardBadRequestCode is the HTTP code returned for type DeleteCardBadRequest
const DeleteCardBadRequestCode int = 400

/*
DeleteCardBadRequest Invalid card value

swagger:response deleteCardBadRequest
*/
type DeleteCardBadRequest struct {
}

// NewDeleteCardBadRequest creates DeleteCardBadRequest with default headers values
func NewDeleteCardBadRequest() *DeleteCardBadRequest {

	return &DeleteCardBadRequest{}
}

// WriteResponse to the client
func (o *DeleteCardBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
