// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCardByNumberParams creates a new GetCardByNumberParams object
//
// There are no default values defined in the spec.
func NewGetCardByNumberParams() GetCardByNumberParams {

	return GetCardByNumberParams{}
}

// GetCardByNumberParams contains all the bound params for the get card by number operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCardByNumber
type GetCardByNumberParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Number of card to return
	  Required: true
	  In: path
	*/
	CardNumber uint64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCardByNumberParams() beforehand.
func (o *GetCardByNumberParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCardNumber, rhkCardNumber, _ := route.Params.GetOK("cardNumber")
	if err := o.bindCardNumber(rCardNumber, rhkCardNumber, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCardNumber binds and validates parameter CardNumber from path.
func (o *GetCardByNumberParams) bindCardNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("cardNumber", "path", "uint64", raw)
	}
	o.CardNumber = value

	return nil
}
