// Code generated by go-swagger; DO NOT EDIT.

package card

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cards/internal/infrastructure/swagger/models"
)

// GetCardByNumberOKCode is the HTTP code returned for type GetCardByNumberOK
const GetCardByNumberOKCode int = 200

/*
GetCardByNumberOK successful operation

swagger:response getCardByNumberOK
*/
type GetCardByNumberOK struct {

	/*
	  In: Body
	*/
	Payload *models.Card `json:"body,omitempty"`
}

// NewGetCardByNumberOK creates GetCardByNumberOK with default headers values
func NewGetCardByNumberOK() *GetCardByNumberOK {

	return &GetCardByNumberOK{}
}

// WithPayload adds the payload to the get card by number o k response
func (o *GetCardByNumberOK) WithPayload(payload *models.Card) *GetCardByNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get card by number o k response
func (o *GetCardByNumberOK) SetPayload(payload *models.Card) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCardByNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCardByNumberBadRequestCode is the HTTP code returned for type GetCardByNumberBadRequest
const GetCardByNumberBadRequestCode int = 400

/*
GetCardByNumberBadRequest Invalid ID supplied

swagger:response getCardByNumberBadRequest
*/
type GetCardByNumberBadRequest struct {
}

// NewGetCardByNumberBadRequest creates GetCardByNumberBadRequest with default headers values
func NewGetCardByNumberBadRequest() *GetCardByNumberBadRequest {

	return &GetCardByNumberBadRequest{}
}

// WriteResponse to the client
func (o *GetCardByNumberBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCardByNumberNotFoundCode is the HTTP code returned for type GetCardByNumberNotFound
const GetCardByNumberNotFoundCode int = 404

/*
GetCardByNumberNotFound Card not found

swagger:response getCardByNumberNotFound
*/
type GetCardByNumberNotFound struct {
}

// NewGetCardByNumberNotFound creates GetCardByNumberNotFound with default headers values
func NewGetCardByNumberNotFound() *GetCardByNumberNotFound {

	return &GetCardByNumberNotFound{}
}

// WriteResponse to the client
func (o *GetCardByNumberNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
